#!/bin/bash

# required in input the JOB ID
JOBNUM=$1

export SLURM_TIME_FORMAT="%s"
LINE_OUT=$(sacct -u $USER -o jobid,nodelist,start,end,consumedenergy -j $JOBNUM | grep $JOBNUM)

# storing useful variables
NODE_NAME=$(echo $LINE_OUT | awk '{print $2}')
T_START=$(echo $LINE_OUT | awk '{print $3}')
T_END=$(echo $LINE_OUT | awk '{print $4}')

dcdbquery -h mb.mont.blanc -r $NODE_NAME-PWR $T_START $T_END > data_tmp

# removing first line
sed '1d' data_tmp > tmpfile; mv tmpfile data_tmp

# removing first column and exchanging ',' with '\t'
cat data_tmp | sed s/$NODE_NAME-PWR,// | sed 's/,/\t/' > data_to_plot

# making a plot
gnuplot make_plot
