#!/bin/bash

# NUM_THREADS="1 2 4 8 16 20"
NUM_THREADS="1 2"

for i in $NUM_THREADS
do
echo "working with $i threads"
export OMP_NUM_THREADS=$i
# echo "OMP_NUM_THREADS=$OMP_NUM_THREADS"

./stream.x | grep Triad: | sed s/Triad:/$i/ | awk '{print $1 "\t" $2}' >> test.out

done