#!/bin/bash

NUM_THREADS="1 2 4 8 10"

module load intel

if [ -f numa_output.txt ]; then
    rm numa_output.txt
fi

# for i in $NUM_THREADS
# do
# export OMP_NUM_THREADS=$i
# count=1
# while [ $count -le 10 ]
# do
#     numactl --cpunodebind=0 --membind=0 ./stream.x | grep Triad: | sed s/Triad:/$i/ | awk '{print $1 "\t" $2}' >> numa00_output.txt
#     count=$((count+1))
# done
# done

for i in $NUM_THREADS
do
export OMP_NUM_THREADS=$i
count=1
while [ $count -le 10 ]
do
    numactl --cpunodebind=0 --membind=1 ./stream.x | grep Triad: | sed s/Triad:/$i/ | awk '{print $1 "\t" $2}' >> numa01_output.txt
    count=$((count+1))
done
done

module load python/2.7.8/gnu/4.9.2
module load numpy/1.9.1/intel/14.0/mkl/11.1/python/2.7.8
module load matplotlib/1.4.3/python/2.7.8/numpy/1.9.1

python numa_plot.py